In [ ]:
import pandas as pd
import numpy as np
import pandas_profiling as pp

In [ ]:
# Read the file
data = pd.read_csv("/content/drive/MyDrive/WinnipegDataset.txt")
data

label        f1       f2        f3  ...     f171     f172     f173     f174
0           1 -13.55900 -21.4070 -11.40400  ...  2.44440  1.67700  0.20988  0.65422
1           1 -12.80200 -20.3350 -10.39900  ...  0.33333  0.84869  0.50617 -0.18898
2           1 -12.43100 -19.9020 -10.07400  ...  0.66667  1.27300  0.30864  0.10483
3           1 -12.68900 -19.5290 -10.02800  ...  0.33333  1.14910  0.38272  0.41603
4           1 -12.68600 -19.2780  -9.81850  ...  0.66667  1.58110  0.20988  0.50000
...       ...       ...      ...       ...  ...      ...      ...      ...      ...
325829      7   2.48230  -7.6870   1.07950  ...  0.22222  1.06090  0.35802  0.63246
325830      7   2.52340  -7.6745   1.08680  ...  4.00000  2.19720  0.11111  0.81224
325831      7  -1.92700 -11.4160  -2.43540  ...  0.33333  1.27300  0.30864  0.31623
325832      7   0.12483 -10.1440  -0.62193  ...  0.11111  0.34883  0.80247  0.18898
325833      7   0.20063 -10.0500  -0.59892  ...  3.00000  2.04320  0.13580  0.72732

[325834 rows x 175 columns]

In [ ]:
# Exponential Data Analysis
data.describe()

label             f1  ...           f173           f174
count  325834.000000  325834.000000  ...  325834.000000  325834.000000
mean        4.062421     -15.143602  ...       0.764646       0.667567
std         1.604617       3.504255  ...       0.273847       0.471260
min         1.000000     -23.971000  ...       0.111110      -1.000000
25%         3.000000     -17.848000  ...       0.506170       0.357140
50%         4.000000     -15.992000  ...       1.000000       1.000000
75%         6.000000     -11.786000  ...       1.000000       1.000000
max         7.000000       2.535600  ...       1.000000       1.000000

[8 rows x 175 columns]

In [ ]:
data.isnull().sum()

label    0
f1       0
f2       0
f3       0
f4       0
        ..
f170     0
f171     0
f172     0
f173     0
f174     0
Length: 175, dtype: int64

In [ ]:
# Seperating data into test & train
X = data.iloc[:,1:]
y = data.iloc[:,:1]

In [ ]:
X.shape, y.shape

((325834, 174), (325834, 1))

In [ ]:
X.head()

f1      f2       f3      f4  ...     f171     f172     f173     f174
0 -13.559 -21.407 -11.4040 -15.248  ...  2.44440  1.67700  0.20988  0.65422
1 -12.802 -20.335 -10.3990 -14.132  ...  0.33333  0.84869  0.50617 -0.18898
2 -12.431 -19.902 -10.0740 -13.598  ...  0.66667  1.27300  0.30864  0.10483
3 -12.689 -19.529 -10.0280 -13.350  ...  0.33333  1.14910  0.38272  0.41603
4 -12.686 -19.278  -9.8185 -13.108  ...  0.66667  1.58110  0.20988  0.50000

[5 rows x 174 columns]

In [ ]:
y.head()

label
0      1
1      1
2      1
3      1
4      1

In [ ]:
# Converting to 1D array
y = np.ravel(y)
y

array([1, 1, 1, ..., 7, 7, 7])

In [ ]:
# Finding Correlation among features
X.corr()

f1        f2        f3  ...      f172      f173      f174
f1    1.000000  0.959623  0.878904  ... -0.022247  0.024887  0.018481
f2    0.959623  1.000000  0.871976  ... -0.010552  0.013447  0.010665
f3    0.878904  0.871976  1.000000  ... -0.028708  0.032470  0.024714
f4    0.940764  0.939766  0.946727  ... -0.024264  0.027487  0.021900
f5    0.966871  0.937634  0.931361  ... -0.016849  0.019921  0.014216
...        ...       ...       ...  ...       ...       ...       ...
f170  0.011096  0.019581  0.006901  ...  0.609302 -0.591693 -0.463072
f171 -0.009695  0.001523 -0.014669  ...  0.898733 -0.897437 -0.759399
f172 -0.022247 -0.010552 -0.028708  ...  1.000000 -0.993672 -0.766471
f173  0.024887  0.013447  0.032470  ... -0.993672  1.000000  0.776471
f174  0.018481  0.010665  0.024714  ... -0.766471  0.776471  1.000000

[174 rows x 174 columns]

In [ ]:
# Create a correlation matrix
corr_matrix = X.corr().abs()
# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(np.bool))
# Find the index of column where correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column]>0.95)]
# Drop Features
X.drop(X[to_drop],axis=1)

f1        f3        f4  ...      f170     f172     f174
0      -13.55900 -11.40400 -15.24800  ...   9.77780  1.67700  0.65422
1      -12.80200 -10.39900 -14.13200  ...   0.33333  0.84869 -0.18898
2      -12.43100 -10.07400 -13.59800  ...   0.88889  1.27300  0.10483
3      -12.68900 -10.02800 -13.35000  ...   0.33333  1.14910  0.41603
4      -12.68600  -9.81850 -13.10800  ...   0.88889  1.58110  0.50000
...          ...       ...       ...  ...       ...      ...      ...
325829   2.48230   1.07950   0.74318  ...   0.22222  1.06090  0.63246
325830   2.52340   1.08680   0.76189  ...  19.55600  2.19720  0.81224
325831  -1.92700  -2.43540  -3.45370  ...   0.33333  1.27300  0.31623
325832   0.12483  -0.62193  -1.54210  ...   0.11111  0.34883  0.18898
325833   0.20063  -0.59892  -1.50120  ...  14.33300  2.04320  0.72732

[325834 rows x 102 columns]

In [ ]:
# Preprocessing the data by StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
# Splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [ ]:
X_train.shape,y_train.shape,

((228083, 174), (228083,))

In [ ]:
X_test.shape,y_test.shape

((97751, 174), (97751,))

In [ ]:
X_train

array([[-0.75776527, -0.6662126 , -0.50705069, ..., -0.11342192,
         0.13812125,  0.70541374],
       [-0.85564644, -0.64130021, -0.66740068, ...,  1.89009532,
        -1.75534635, -1.75206706],
       [-0.19559063,  0.21558723, -0.34731272, ...,  1.55331898,
        -1.39467021, -1.01555066],
       ...,
       [-1.43579925, -1.20022564, -1.14416649, ..., -0.83993826,
         0.85943703,  0.70541374],
       [-0.43016299, -0.70814433, -0.16645996, ..., -0.83993826,
         0.85943703,  0.70541374],
       [-0.17333194, -0.38650322, -0.26009946, ..., -0.83993826,
         0.85943703,  0.70541374]])

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([5, 5, 3, ..., 5, 4, 2])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[11725     0    13    29     1     2     7]
 [    0  1093     1     1     0     0     0]
 [    3     0 22709    11     6     9     0]
 [   12     0    16 22158    28    15     0]
 [    3     0     9    33 13927    74     8]
 [    4     0     3    23    48 25443     5]
 [    6     0     0     0     4     2   320]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     11777
           2       1.00      1.00      1.00      1095
           3       1.00      1.00      1.00     22738
           4       1.00      1.00      1.00     22229
           5       0.99      0.99      0.99     14054
           6       1.00      1.00      1.00     25526
           7       0.94      0.96      0.95       332

    accuracy                           1.00     97751
   macro avg       0.99      0.99      0.99     97751
weighted avg       1.00      1.00      1.00     97751

0.9961534920358871


In [ ]:
# Importing Supprot Vector Machine
from sklearn import svm
svc = svm.SVC()
svc.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svc.predict(X_test)
y_pred

array([5, 5, 3, ..., 5, 4, 2])

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[11738     1    12    15     0     1    10]
 [    0  1094     0     0     0     0     1]
 [    1     0 22717     1     3    10     6]
 [    8     0     9 22176    30     6     0]
 [    1     0     2    19 13967    59     6]
 [    3     0     3    13    56 25443     8]
 [    1     0     0     0     1     2   328]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     11777
           2       1.00      1.00      1.00      1095
           3       1.00      1.00      1.00     22738
           4       1.00      1.00      1.00     22229
           5       0.99      0.99      0.99     14054
           6       1.00      1.00      1.00     25526
           7       0.91      0.99      0.95       332

    accuracy                           1.00     97751
   macro avg       0.99      1.00      0.99     97751
weighted avg       1.00      1.00      1.00     97751

0.9970537385806795
